services:
    db:
        image: postgres:15 # Utilisation de l'image officielle de PostgreSQL
        container_name: postgres_db # Nom du conteneur pour PostgreSQL
        ports:
            - "5432:5432" # Exposition du port 5432 pour la connexion à la base de données
        environment:
            POSTGRES_USER: postgres # Nom d'utilisateur de PostgreSQL
            POSTGRES_PASSWORD: postgres # Mot de passe de PostgreSQL
            POSTGRES_DB: my_database # Nom de la base de données par défaut
        volumes:
            - db_data:/var/lib/postgresql/data # Volume persistant pour les données PostgreSQL

volumes:
    db_data: # Volume persistant pour les données de la base de données PostgreSQL
